/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe.management.system;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import javax.swing.table.DefaultTableModel;
import dao.UserDao;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.user;

/**
 *
 * @author ridwa
 */
public class Verify extends javax.swing.JFrame {

    /**
     * Creates new form Verify
     */
    public Verify() {
        initComponents();
    }

    public void getAllRecords(String email) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ArrayList<user> list = UserDao.getAllRecords(email);
        Iterator<user> itr = list.iterator();
        while (itr.hasNext()) {
            user userObj = itr.next();
            if (!userObj.getEmail().equals("ridwanspeed8@gmail.com")) {
                dtm.addRow(new Object[]{
                    userObj.getId(),
                    userObj.getName(),
                    userObj.getEmail(),
                    userObj.getMobileNumber(),
                    userObj.getAddress(),
                    userObj.getSecurityQuestion(),
                    userObj.getStatus()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btn_cetak = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        jLabel1.setText("Verifikasi User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 25, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1324, 13, 30, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        txt_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 310, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Mobile Number", "Address", "Security Question", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 221, 1342, -1));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel3.setText("*klik pada baris untuk mengubah status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 670, -1, -1));

        btn_cetak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String email = txt_email.getText();
        getAllRecords(email);
    }//GEN-LAST:event_formComponentShown

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String email = model.getValueAt(index, 2).toString();
        String status = model.getValueAt(index, 6).toString();
        if (status.equals("true")) {
            status = "false";
        } else {
            status = "true";
        }
        int a = JOptionPane.showConfirmDialog(null, "Do  you want to change status of " + email + "", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            UserDao.changeStatus(email, status);
            setVisible(false);
            new Verify().setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat dayFormat = new SimpleDateFormat("EEEE", new Locale("id", "ID"));
    Date date = new Date();
    String todayDate = dFormat.format(date);
    String todayDay = dayFormat.format(date);
    String createdBy = "admin"; // Replace with actual user info if available
    String path = "E:\\"; // Change the path as required
    Document doc = new Document();

    try {
        PdfWriter.getInstance(doc, new FileOutputStream(path + "Verification_" + todayDate + ".pdf"));
        doc.open();

        // Add content to PDF
        Paragraph cafeName = new Paragraph("Cafe Management System\n", new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD));
        cafeName.setAlignment(Element.ALIGN_CENTER);
        doc.add(cafeName);

        Paragraph starLine = new Paragraph("*******************************************************************************************************");
        doc.add(starLine);

        Paragraph verificationInfo = new Paragraph("Detail Customer\n", new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD));
        verificationInfo.setAlignment(Element.ALIGN_CENTER);
        doc.add(verificationInfo);
        doc.add(starLine);

        PdfPTable tbl = new PdfPTable(7);
        tbl.addCell("ID");
        tbl.addCell("Name");
        tbl.addCell("Email");
        tbl.addCell("Mobile Number");
        tbl.addCell("Address");
        tbl.addCell("Security Question");
        tbl.addCell("Status");

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            String id = jTable1.getValueAt(i, 0).toString();
            String name = jTable1.getValueAt(i, 1).toString();
            String userEmail = jTable1.getValueAt(i, 2).toString();
            String mobile = jTable1.getValueAt(i, 3).toString();
            String address = jTable1.getValueAt(i, 4).toString();
            String securityQuestion = jTable1.getValueAt(i, 5).toString();
            String status = jTable1.getValueAt(i, 6).toString();
            tbl.addCell(id);
            tbl.addCell(name);
            tbl.addCell(userEmail);
            tbl.addCell(mobile);
            tbl.addCell(address);
            tbl.addCell(securityQuestion);
            tbl.addCell(status);
        }

        doc.add(tbl);
        doc.add(starLine);

        Paragraph thanksMsg = new Paragraph("Terimakasih, atas kunjungan Anda.", new Font(Font.FontFamily.TIMES_ROMAN, 14, Font.ITALIC));
        thanksMsg.setAlignment(Element.ALIGN_CENTER);
        doc.add(thanksMsg);

        // Add date and signature at the bottom right
        Paragraph dateAndSignature = new Paragraph("Jakarta, " + todayDay + ", " + todayDate + "\n\n(Akbar Coffee Shop)", new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL));
        dateAndSignature.setAlignment(Element.ALIGN_RIGHT);
        doc.add(dateAndSignature);

        // Close the document before opening PDF
        doc.close();

        // Open the generated PDF after it's closed
        OpenPdf.openById("Verification_" + todayDate);
        JOptionPane.showMessageDialog(null, "Detail Customers successfully generated.", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_btn_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
}
